import OmegaBalance
import OmegaBalance.Examples

#print axioms OmegaBalance.bigOmega_zero
#print axioms OmegaBalance.bigOmega_one
#print axioms OmegaBalance.bigOmega_prime
#print axioms OmegaBalance.bigOmega_mul
#print axioms OmegaBalance.bigOmega_prime_pow
#print axioms OmegaBalance.neighborDiff_eq_zero_iff
#print axioms OmegaBalance.neighborDiff_pos_iff
#print axioms OmegaBalance.neighborDiff_neg_iff
#print axioms OmegaBalance.omegaDiff_eq_zero_iff
#print axioms OmegaBalance.isOmegaBalancedPrime_iff
#print axioms OmegaBalance.bigOmega_double_diff
#print axioms OmegaBalance.prime_mod_two_eq_one
#print axioms OmegaBalance.omegaDiff_eq_half_diff
#print axioms OmegaBalance.omegaDiff_prime_eq_half_diff
#print axioms OmegaBalance.isOmegaBalanced_iff_half
#print axioms OmegaBalance.omegaSum_eq_bigOmega_product
#print axioms OmegaBalance.omegaSum_eq_bigOmega_sq_sub_one
#print axioms OmegaBalance.omegaSum_add_omegaDiff
#print axioms OmegaBalance.omegaSum_sub_omegaDiff
#print axioms OmegaBalance.v3_two
#print axioms OmegaBalance.v3_three
#print axioms OmegaBalance.v3_four
#print axioms OmegaBalance.v3_eight
#print axioms OmegaBalance.v3_fourteen
#print axioms OmegaBalance.v3_six
#print axioms OmegaBalance.v3_twelve
#print axioms OmegaBalance.v3_eighteen
#print axioms OmegaBalance.v3_twenty_seven
#print axioms OmegaBalance.v3_twenty
#print axioms OmegaBalance.f3_three
#print axioms OmegaBalance.f3_five
#print axioms OmegaBalance.f3_seven
#print axioms OmegaBalance.f3_thirteen
#print axioms OmegaBalance.twin_five_seven_example
#print axioms OmegaBalance.twin_seventeen_nineteen_example
#print axioms OmegaBalance.exceptional_twin_three
#print axioms OmegaBalance.bigOmega_four
#print axioms OmegaBalance.bigOmega_six
#print axioms OmegaBalance.bigOmega_eight
#print axioms OmegaBalance.five_isOmegaBalancedPrime
#print axioms OmegaBalance.omegaDiff_twin_five_seven
#print axioms OmegaBalance.opposite_f3_not_sufficient_for_twins
#print axioms OmegaBalance.not_three_dvd_prime
#print axioms OmegaBalance.prime_mod_three
#print axioms OmegaBalance.twin_mod_three
#print axioms OmegaBalance.twin_mod_six
#print axioms OmegaBalance.six_dvd_twin_center
#print axioms OmegaBalance.twin_six_mul_form
#print axioms OmegaBalance.f3_of_mod_three_two
#print axioms OmegaBalance.f3_of_mod_three_one
#print axioms OmegaBalance.f3_ne_zero_of_prime
#print axioms OmegaBalance.f3_pos_iff_mod_three
#print axioms OmegaBalance.f3_neg_iff_mod_three
#print axioms OmegaBalance.f3_pair_values_of_mod_three
#print axioms OmegaBalance.f3_opposite_of_mod_three
#print axioms OmegaBalance.f3_twin_values
#print axioms OmegaBalance.f3_twin
#print axioms OmegaBalance.IsTwinPrime.f3_opposite
#print axioms OmegaBalance.f3_twin_signs
#print axioms OmegaBalance.f3_twin_abs_eq
#print axioms OmegaBalance.f3_twin_natAbs_eq
#print axioms OmegaBalance.f3_twin_mul_neg
#print axioms OmegaBalance.f3_eq_valuationDiff
#print axioms OmegaBalance.valuation_eq_padicValNat
#print axioms OmegaBalance.valuation_zero
#print axioms OmegaBalance.valuation_one
#print axioms OmegaBalance.valuation_eq_zero_of_not_dvd
#print axioms OmegaBalance.valuation_pos_of_dvd
#print axioms OmegaBalance.valuation_pos_iff_dvd
#print axioms OmegaBalance.valuation_mul
#print axioms OmegaBalance.valuation_prime_pow
#print axioms OmegaBalance.v3_zero
#print axioms OmegaBalance.v3_one
#print axioms OmegaBalance.v3_eq_zero_of_not_dvd
#print axioms OmegaBalance.v3_pos_of_dvd
#print axioms OmegaBalance.v3_pos_iff_dvd
#print axioms OmegaBalance.v3_mul
#print axioms OmegaBalance.v3_pow_three

#print axioms OmegaBalance.v3Int_nat
#print axioms OmegaBalance.v3Int_neg
#print axioms OmegaBalance.f3Int_nat
#print axioms OmegaBalance.f3Int_neg
#print axioms OmegaBalance.f3Int_neg_nat
#print axioms OmegaBalance.f3_of_mod_three_zero
#print axioms OmegaBalance.f3_eq_zero_iff_three_dvd
#print axioms OmegaBalance.f3_ne_zero_of_not_dvd
#print axioms OmegaBalance.f3_abs_eq_neighbor_sum
#print axioms OmegaBalance.f3_abs_eq_v3_sq_sub_one
#print axioms OmegaBalance.f3_sq
#print axioms OmegaBalance.v3_eq_one_of_mod_nine
#print axioms OmegaBalance.v3_quad_plus_one
#print axioms OmegaBalance.v3_quad_minus_one
#print axioms OmegaBalance.f3_cube_of_mod_three_one
#print axioms OmegaBalance.f3_cube_of_mod_three_two
#print axioms OmegaBalance.f3_cube

#print axioms OmegaBalance.f3Side_values
#print axioms OmegaBalance.f3_eq_side_mul_natAbs
#print axioms OmegaBalance.f3_center_pos
#print axioms OmegaBalance.f3_center_valuation
#print axioms OmegaBalance.v3Int_eq_padicValRat
#print axioms OmegaBalance.v3Int_add_ge_min
#print axioms OmegaBalance.v3Int_add_eq_min
#print axioms OmegaBalance.v3Int_sub_eq_min
#print axioms OmegaBalance.f3_adjusted_gap_valuation
#print axioms OmegaBalance.f3_reflection
#print axioms OmegaBalance.f3Side_mul
#print axioms OmegaBalance.f3_iterated_cube_pos
#print axioms OmegaBalance.f3_iterated_cube_neg
#print axioms OmegaBalance.v3_add_ge_min
#print axioms OmegaBalance.v3_add_eq_min
#print axioms OmegaBalance.f3_mul_depth
